version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t nszknao/react-boilerplate -f Dockerfile.dev .
      - run: docker run nszknao/react-boilerplate yarn test --coverage --watchAll=false
